modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="Unlicense"

[[mods]] #mandatory
	modId="mineshot_reforge" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="Mineshot Reforge" #mandatory
	#displayURL="https://github.com/pascallj/mineshot-revived" #optional
	credits="Barracuda, Pascal Roeleven" #optional
	authors="TexTrue, TexTrueStudio" #optional
	description='''
    A reforge version of Mineshot: "A revamped version of Notch's huge screenshot function".
    '''

		[[dependencies.mineshot_reforge]] #optional
		    modId="forge" #mandatory
		    mandatory=true #mandatory
		    versionRange="[32,)" #mandatory
		    ordering="NONE"
		    side="BOTH"
		[[dependencies.mineshot_reforge]]
		    modId="minecraft"
		    mandatory=true
		    versionRange="[1.16,1.16.5]"
		    ordering="NONE"
		    side="BOTH"
